channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - scipy
     - opencv-python
     - face_recognition
     - numpy
     - joblib
     - pip
     - pip:
       - install joblib